baseURL: "/"
enableRobotsTXT: True
languageCode: "en-us"
title: "Crossplane"
theme: "geekboot"
enableGitInfo: true
uglyurls: false
disableKinds:
  - taxonomy
  - term

outputs:
  home:
  - html
  section:
  - html
  - rss
  taxonomy:
  term:


ignoreFiles:
- README.md

build:
  # writeStats: true

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9
  highlight:
    codeFences: true
    noClasses: false
    linenos: true
    anchorLineNos: true
    lineNumbersInTable: false

module:
  mounts:
  - source: content
    target: content
  - source: assets
    target: assets
  - source: content
    target: assets/content
    includeFiles:
      - "**/**.png"
      - "**/**.jpg"
      - "**/**.jpeg"
      - "**/**.gif"
  - source: content
    target: data/crds/
    includeFiles:
      - "**/api/**.yaml"

security:
  funcs:
    getenv:
      - ^CONTEXT
      - ^REVIEW_ID

params:
  latest: "1.14"
  upboundLink: "https://www.upbound.io/"
  slackLink: "https://slack.crossplane.io/"
  githubLink: "https://github.com/crossplane/crossplane"
  twitterLink: "https://twitter.com/crossplane_io"
  forumLink: "https://groups.google.com/forum/#!forum/crossplane-dev"
  youtubeLink: "https://www.youtube.com/channel/UC19FgzMBMqBro361HbE46Fw"
  podcastLink: "https://www.youtube.com/playlist?list=PL510POnNVaaYFuK-B_SIUrpIonCtLVOzT"
  blogLink: "https://blog.crossplane.io/"
  communityMeetingLink: "https://github.com/crossplane/crossplane/#get-involved"
  cncfLink: "https://www.cncf.io/"
  prodFormLink: "https://docs.google.com/forms/d/e/1FAIpQLSev-5clADSdkwi_wiFqBCAECeIoAQDE91chBbeWbvyTjRCeYg/viewform"
  infoMailToLink: "mailto:info@crossplane.io"
  upboundGithubLink: "https://github.com/upbound"
  docs: true
  repoLink: "https://github.com/crossplane/crossplane"
  anchors:
    min: 2
    max: 5
  description: "Crossplane lets you build a control plane with Kubernetes-style declarative and API-driven configuration and management for anything."
