name: Validate content with Vale

on:
  pull_request:
    paths:
      - 'content/**'

  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  lint-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the docs repo
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: content/**

      - name: Run Vale on changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: errata-ai/vale-action@reviewdog
        with:
          version: 3.13.0
          files: ${{ steps.changed-files.outputs.all_changed_files }}
          reporter: github-pr-review
          fail_on_error: true
          filter_mode: nofilter
          vale_flags: '--config=./utils/vale/.vale.ini'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
